permissions:
  contents: read
  actions: read
  pull-requests: read

on:
  pull_request:
    types: [opened, edited, closed, reopened]
  workflow_run:
    workflows: [CI]
    types: [completed]
  workflow_dispatch:

env:
  NODE_TLS_REJECT_UNAUTHORIZED: 0

jobs:
  octane_integration_job:
    runs-on: self-hosted
    name: OctaneIntegration#${{github.event.action}}#${{github.event.workflow_run.id}}
    steps:
      - name: GitHub Actions ALM Octane Integration
        uses: MicroFocus/alm-octane-github-actions-integration@v1
        id: gitHubActionsIntegration
        with:
          octaneUrl: https://felix-1.almoctane.com/ui/
          octaneSharedSpace: 1001
          octaneWorkspace: 1003
          octaneClientId: ${{secrets.ALM_OCTANE_CLIENT_ID}}
          octaneClientSecret: ${{secrets.ALM_OCTANE_CLIENT_SECRET}}
          githubToken: ${{secrets.GITHUB_TOKEN}}
          serverBaseUrl: https://github.com/vivienknecht/uft-tests/
          pipelineNamePattern: '${workflow_name}'
          unitTestResultsGlobPattern: "**/*.xml"
      - name: Log workflow execution parameters
        run: |
           echo "execution_parameter:: $(echo '${{ toJson(github.event.inputs) }}' | jq -c .)"
